# Run tests on main pull request
name: On Main Pull Request
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        uses: ./.github/actions/unit-tests
        with:
          working-directory: "./"
